"""empty message

Revision ID: 890327142404
Revises: 4119075ad777
Create Date: 2024-01-21 17:27:43.683787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890327142404'
down_revision = '4119075ad777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
